--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapiissuecomment_info
  description: ApiManagementListApiIssueComments
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    issue_id: myIssue
  