--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproduct_info
  description: ApiManagementListProducts
  code:
    resource_group: myResourceGroup
    name: myService
  