--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementservice
  description: ApiManagementCreateServiceWithSystemCertificates
  code:
    resource_group: myResourceGroup
    name: myService
    tags:
      tag1: value1
      tag2: value2
      tag3: value3
    certificates:
      - encoded_certificate: '*******Base64 encoded Certificate******************'
        certificate_password: Password
        store_name: CertificateAuthority
    publisher_email: apim@autorestsdk.com
    publisher_name: autorestsdk
    sku_name: Basic
    sku_capacity: '1'
    location: Central US
  