--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementbackend_info
  description: ApiManagementListBackends
  code:
    resource_group: myResourceGroup
    name: myService
  