--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementquotabyperiodkey_info
  description: ApiManagementGetQuotaCounterKeysByQuotaPeriod
  code:
    resource_group: myResourceGroup
    name: myService
    quota_counter_key: myQuota
    quota_period_key: myPeriod
  