--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_cosmosdbdatabaseaccount
  description: CosmosDBDatabaseAccountCreateMax
  code:
    resource_group: myResourceGroup
    name: myDatabaseAccount
    create_update_parameters:
      location: westus
      tags: {}
      kind: GlobalDocumentDB
      properties:
        databaseAccountOfferType: Standard
        ipRangeFilter: 10.10.10.10
        isVirtualNetworkFilterEnabled: true
        virtualNetworkRules:
          - id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/virtualNetworks/{{
              virtual_network_name }}/subnets/{{ subnet_name }}
            ignoreMissingVNetServiceEndpoint: false
        locations:
          - failoverPriority: '0'
            locationName: southcentralus
            isZoneRedundant: false
          - failoverPriority: '1'
            locationName: eastus
            isZoneRedundant: false
        consistencyPolicy:
          defaultConsistencyLevel: BoundedStaleness
          maxIntervalInSeconds: '10'
          maxStalenessPrefix: '200'
  