--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_cosmosdbdatabaseaccount
  description: CosmosDBDatabaseAccountCreateMin
  code:
    resource_group: myResourceGroup
    name: myDatabaseAccount
    create_update_parameters:
      location: westus
      properties:
        databaseAccountOfferType: Standard
        locations:
          - failoverPriority: '0'
            locationName: southcentralus
  