--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproductapi
  description: ApiManagementDeleteProductApi
  code:
    resource_group: myResourceGroup
    name: myService
    product_id: myProduct
    api_id: myApis
    state: absent
  