--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementtag_info
  description: ApiManagementListTags
  code:
    resource_group: myResourceGroup
    name: myService
  