--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapi
  description: ApiManagementCreateSoapPassThroughApiUsingWsdlImport
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    path: currency
    value: 'http://www.webservicex.net/CurrencyConvertor.asmx?WSDL'
    format: wsdl-link
    wsdl_selector:
      wsdl_service_name: CurrencyConvertor
      wsdl_endpoint_name: CurrencyConvertorSoap
    api_type: soap
  