--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementemailtemplate
  description: ApiManagementCreateEmailTemplate
  code:
    resource_group: myResourceGroup
    service_name: myService
    name: myTemplate
    subject: Your request for $IssueName was successfully received.
  