--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementpolicy
  description: ApiManagementDeletePolicy
  code:
    resource_group: myResourceGroup
    name: myService
    policy_id: myPolicy
    state: absent
  