--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_privatelinkservice
  description: Create private link service
  code:
    resource_group: myResourceGroup
    name: myPrivateLinkService
    location: eastus
    load_balancer_frontend_ip_configurations:
      - id: >-
          /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
          }}/providers/Microsoft.Network/loadBalancers/{{ load_balancer_name
          }}/frontendIPConfigurations/{{ frontend_ipconfiguration_name }}
    ip_configurations:
      - private_ip_address: 10.0.1.4
        private_ipallocation_method: Static
        subnet:
          id: >-
            /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group
            }}/providers/Microsoft.Network/virtualNetworks/{{ virtual_network_name
            }}/subnets/{{ subnet_name }}
        private_ip_address_version: IPv4
        name: fe-lb
    visibility:
      subscriptions:
        - subscription1
        - subscription2
        - subscription3
    auto_approval:
      subscriptions:
        - subscription1
        - subscription2
    fqdns:
      - fqdn1
      - fqdn2
      - fqdn3
  