--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_frontdoorroutingrule
  description: Create or update specific Forwarding Routing Rule
  code:
    resource_group: myResourceGroup
    front_door_name: myFrontDoor
    name: myRoutingRule
    routing_rule_parameters:
      name: routingRule1
      properties:
        frontendEndpoints:
          - id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/frontDoors/{{
              front_door_name }}/frontendEndpoints/{{ frontend_endpoint_name }}
          - id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/frontDoors/{{
              front_door_name }}/frontendEndpoints/{{ frontend_endpoint_name }}
        acceptedProtocols:
          - Http
        patternsToMatch:
          - /*
        routeConfiguration:
          '@odata.type': '#Microsoft.Azure.FrontDoor.Models.FrontdoorForwardingConfiguration'
          backendPool:
            id: >-
              /subscriptions/{{ subscription_id }}/resourceGroups/{{
              resource_group }}/providers/Microsoft.Network/frontDoors/{{
              front_door_name }}/backendPools/{{ backend_pool_name }}
        enabledState: Enabled
  