--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapischema
  description: ApiManagementDeleteApiSchema
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    schema_id: mySchema
    state: absent
  