--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementdiagnostic_info
  description: ApiManagementListDiagnostics
  code:
    resource_group: myResourceGroup
    name: myService
  