--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapidiagnosticlogger
  description: ApiManagementDeleteApiDiagnosticLogger
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    diagnostic_id: myDiagnostic
    loggerid: myLogger
    state: absent
  