--- !ruby/object:Provider::Azure::Example
resource: azure_rm_batchaccount
description: Delete Batch Account
prerequisites:
  - !ruby/object:Provider::Azure::ExampleReference
    product: storageaccount
    example: delete
properties:
  resourceGroup: "<%= get_resource_name('resourceGroups', 'resource_group') -%>"
  name: "<%= get_resource_name('batchAccounts', 'batch_account_name', 'ba') -%>"
  state: absent