--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementservicesku_info
  description: ApiManagementListSKUs
  code:
    resource_group: myResourceGroup
    name: myService
  