--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_servicebusdisasterrecoveryconfig_info
  description: SBAliasList
  code:
    resource_group: myResourceGroup
    namespace_name: my
    alias: sdk-DisasterRecovery-3814
  