--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapidiagnostic
  description: ApiManagementCreateApiDiagnostic
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    diagnostic_id: myDiagnostic
    always_log: allErrors
    logger_id: /loggers/applicationinsights
    sampling:
      sampling_type: fixed
      percentage: '50'
    frontend:
      request:
        headers:
          - Content-type
        body:
          bytes: '512'
      response:
        headers:
          - Content-type
        body:
          bytes: '512'
    backend:
      request:
        headers:
          - Content-type
        body:
          bytes: '512'
      response:
        headers:
          - Content-type
        body:
          bytes: '512'
  