--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapidiagnostic
  description: ApiManagementDeleteApiDiagnostic
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    diagnostic_id: myDiagnostic
    state: absent
  