--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementservice
  description: ApiManagementCreateServiceHavingMsi
  code:
    resource_group: myResourceGroup
    name: myService
    tags:
      tag1: value1
      tag2: value2
      tag3: value3
    publisher_email: apim@autorestsdk.com
    publisher_name: autorestsdk
    sku:
      name: Consumption
    identity:
      type: SystemAssigned
    location: West US
  