--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchapplicationpackage
  description: ApplicationPackageDelete
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    application_name: myApplication
    version_name: myVersion
    state: absent
  