--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapioperation
  description: ApiManagementCreateApiOperation
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    operation_id: myOperation
    template_parameters: []
    description: This can only be done by the logged in user.
    request:
      description: Created user object
      query_parameters: []
      headers: []
      representations:
        - content_type: application/json
          schema_id: 592f6c1d0af5840ca8897f0c
          type_name: User
    responses:
      - status_code: '200'
        description: successful operation
        representations:
          - content_type: application/xml
          - content_type: application/json
        headers: []
    display_name: createUser2
    method: POST
    url_template: /user1
  