--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapioperation
  description: ApiManagementDeleteApiOperation
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    operation_id: myOperation
    state: absent
  