--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_batchpool
  description: UpdatePool - Resize Pool
  code:
    resource_group: myResourceGroup
    account_name: myBatchAccount
    pool_name: myPool
    scale_settings:
      fixed_scale:
        resize_timeout: PT8M
        target_dedicated_nodes: '5'
        target_low_priority_nodes: '0'
        node_deallocation_option: TaskCompletion
  