--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapioperationpolicy
  description: ApiManagementCreateApiOperationPolicy
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    operation_id: myOperation
    policy_id: myPolicy
    value: >-
      <policies> <inbound /> <backend>    <forward-request />  </backend> 
      <outbound /></policies>
    format: xml
  