--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementtagresource_info
  description: ApiManagementListTagResources
  code:
    resource_group: myResourceGroup
    name: myService
  