--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapiissue_info
  description: ApiManagementListApiIssues
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
  