--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapipolicy_info
  description: ApiManagementGetApiPolicy
  code:
    resource_group: myResourceGroup
    name: myService
    api_id: myApis
    policy_id: myPolicy
  