--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementopenidconnectprovider_info
  description: ApiManagementGetOpenIdConnectProvider
  code:
    resource_group: myResourceGroup
    name: myService
    opid: myOpenidConnectProvider
  