--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementproductgroup
  description: ApiManagementCreateProductGroup
  code:
    resource_group: myResourceGroup
    name: myService
    product_id: myProduct
    group_id: myGroup
  