--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementgroup
  description: ApiManagementDeleteGroup
  code:
    resource_group: myResourceGroup
    name: myService
    group_id: myGroup
    state: absent
  