--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_computegalleryimage
  description: Create or update a simple gallery image.
  code:
    resource_group: myResourceGroup
    gallery_name: myGallery
    name: myImage
    gallery_image:
      location: West US
      properties:
        osType: Windows
        osState: Generalized
        identifier:
          publisher: myPublisherName
          offer: myOfferName
          sku: mySkuName
  