--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementbackend
  description: ApiManagementCreateBackendProxyBackend
  code:
    resource_group: myResourceGroup
    service_name: myService
    backend_id: myBackend
    description: description5308
    credentials:
      query:
        sv:
          - xx
          - bb
          - cc
      header:
        x-my-1:
          - val1
          - val2
      authorization:
        scheme: Basic
        parameter: opensesma
    proxy:
      url: 'http://192.168.1.1:8080'
      username: Contoso\admin
      password: opensesame
    tls:
      validate_certificate_chain: true
      validate_certificate_name: true
    url: 'https://backendname2644/'
    protocol: http
  