--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementapipolicy
  description: ApiManagementCreateApiPolicy
  code:
    resource_group: myResourceGroup
    service_name: myService
    api_id: myApi
    policy_id: myPolicy
    value: >-
      <policies> <inbound /> <backend>    <forward-request />  </backend> 
      <outbound /></policies>
    format: xml
  