--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_managementgroupsubscription
  description: DeleteSubscriptionFromManagementGroup
  code:
    group_id: myManagementGroup
    state: absent
  