--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementbackend
  description: ApiManagementCreateBackendServiceFabric
  code:
    resource_group: myResourceGroup
    name: myService
    backendid: myBackend
    description: Service Fabric Test App 1
    service_fabric_cluster:
      client_certificatethumbprint: EBA029198AA3E76EF0D70482626E5BCF148594A6
      max_partition_resolution_retries: '5'
      management_endpoints:
        - 'https://somecluster.com'
      server_x509names:
        - name: ServerCommonName1
          issuer_certificate_thumbprint: IssuerCertificateThumbprint1
    url: 'fabric:/mytestapp/mytestservice'
    protocol: http
  