--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_apimanagementlogger
  description: ApiManagementCreateEHLogger
  code:
    resource_group: myResourceGroup
    service_name: myService
    logger_id: myLogger
    logger_type: azureEventHub
    description: adding a new logger
    credentials:
      name: hydraeventhub
      connectionString: >-
        Endpoint=sb://hydraeventhub-ns.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=********=
  