// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package azurerm



func resourceArmBatchApplication() *schema.Resource {
    return &schema.Resource{
        Create: resourceArmBatchApplicationCreate,
        Read: resourceArmBatchApplicationRead,
        Update: resourceArmBatchApplicationUpdate,
        Delete: resourceArmBatchApplicationDelete,

        Importer: &schema.ResourceImporter{
            State: schema.ImportStatePassthrough,
        },


        Schema: map[string]*schema.Schema{
            "name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
            },

            "account_name": {
                Type: schema.TypeString,
                Required: true,
                ForceNew: true,
            },

            "resource_group": resourceGroupNameSchema(),

            "allow_updates": {
                Type: schema.TypeBool,
                Optional: true,
            },

            "default_version": {
                Type: schema.TypeString,
                Optional: true,
            },

            "display_name": {
                Type: schema.TypeString,
                Optional: true,
            },
        },
    }
}

func resourceArmBatchApplicationCreate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).applicationClient
    ctx := meta.(*ArmClient).StopContext

    name := d.Get("name").(string)
    resourceGroup := d.Get("resource_group").(string)
    AccountName := d.Get("account_name").(string)

    if requireResourcesToBeImported {
        resp, err := client.Get(ctx, resourceGroup, AccountName, name)
        if err != nil {
            if !utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Error checking for present of existing Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
            }
        }
        if !utils.ResponseWasNotFound(resp.Response) {
            return tf.ImportAsExistsError("azurerm_batch_application", *resp.ID)
        }
    }

    allowUpdates := d.Get("allow_updates").(bool)
    defaultVersion := d.Get("default_version").(string)
    displayName := d.Get("display_name").(string)

    Parameters := batch.Application{
        Properties: &batch.ApplicationProperties{
            AllowUpdates: utils.Bool(allowUpdates),
            DefaultVersion: utils.String(defaultVersion),
            DisplayName: utils.String(displayName),
        },
    }


    if _, err := client.Create(ctx, resourceGroup, AccountName, name, Parameters); err != nil {
        return fmt.Errorf("Error creating Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
    }


    resp, err := client.Get(ctx, resourceGroup, AccountName, name)
    if err != nil {
        return fmt.Errorf("Error retrieving Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
    }
    if resp.ID == nil {
        return fmt.Errorf("Cannot read Batch Application %q (Account Name %q / Resource Group %q) ID", name, AccountName, resourceGroup)
    }
    d.SetId(*resp.ID)

    return resourceArmBatchApplicationRead(d, meta)
}

func resourceArmBatchApplicationRead(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).applicationClient
    ctx := meta.(*ArmClient).StopContext

    id, err := parseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    AccountName := id.Path["batchAccounts"]
    name := id.Path["applications"]

    resp, err := client.Get(ctx, resourceGroup, AccountName, name)
    if err != nil {
        if utils.ResponseWasNotFound(resp.Response) {
            log.Printf("[INFO] Batch Application %q does not exist - removing from state", d.Id())
            d.SetId("")
            return nil
        }
        return fmt.Errorf("Error reading Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
    }


    d.Set("name", name)
    d.Set("resource_group", resourceGroup)
    d.Set("account_name", AccountName)

    return nil
}

func resourceArmBatchApplicationUpdate(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).applicationClient
    ctx := meta.(*ArmClient).StopContext

    name := d.Get("name").(string)
    resourceGroup := d.Get("resource_group").(string)
    AccountName := d.Get("account_name").(string)
    allowUpdates := d.Get("allow_updates").(bool)
    defaultVersion := d.Get("default_version").(string)
    displayName := d.Get("display_name").(string)

    Parameters := batch.Application{
        Properties: &batch.ApplicationProperties{
            AllowUpdates: utils.Bool(allowUpdates),
            DefaultVersion: utils.String(defaultVersion),
            DisplayName: utils.String(displayName),
        },
    }


    if _, err := client.Update(ctx, resourceGroup, AccountName, name, Parameters); err != nil {
        return fmt.Errorf("Error updating Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
    }

    return resourceArmBatchApplicationRead(d, meta)
}

func resourceArmBatchApplicationDelete(d *schema.ResourceData, meta interface{}) error {
    client := meta.(*ArmClient).applicationClient
    ctx := meta.(*ArmClient).StopContext


    id, err := parseAzureResourceID(d.Id())
    if err != nil {
        return err
    }
    resourceGroup := id.ResourceGroup
    AccountName := id.Path["batchAccounts"]
    name := id.Path["applications"]

    if _, err := client.Delete(ctx, resourceGroup, AccountName, name); err != nil {
        return fmt.Errorf("Error deleting Batch Application %q (Account Name %q / Resource Group %q): %+v", name, AccountName, resourceGroup, err)
    }

    return nil
}
