// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
    "fmt"
    "testing"

    "github.com/hashicorp/terraform/helper/resource"
    "github.com/hashicorp/terraform/terraform"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
    "github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)

func TestAccAzureRMBatchApplication_basic(t *testing.T) {
    resourceName := "azurerm_batch_application.test"
    ri := tf.AccRandTimeInt()
    location := testLocation()

    resource.ParallelTest(t, resource.TestCase{
        PreCheck:     func() { testAccPreCheck(t) },
        Providers:    testAccProviders,
        CheckDestroy: testCheckAzureRMBatchApplicationDestroy,
        Steps: []resource.TestStep{
            {
                Config: testAccAzureRMBatchApplication_basic(ri, location),
                Check: resource.ComposeTestCheckFunc(
                    testCheckAzureRMBatchApplicationExists(resourceName),
                ),
            },
            {
                ResourceName:      resourceName,
                ImportState:       true,
                ImportStateVerify: true,
            },
        },
    })
}


func testCheckAzureRMBatchApplicationExists(resourceName string) resource.TestCheckFunc {
    return func(s *terraform.State) error {
        rs, ok := s.RootModule().Resources[resourceName]
        if !ok {
            return fmt.Errorf("Batch Application not found: %s", resourceName)
        }

        name := rs.Primary.Attributes["name"]
        resourceGroup := rs.Primary.Attributes["resource_group_name"]
        accountName := rs.Primary.Attributes["account_name"]

        client := testAccProvider.Meta().(*ArmClient).applicationClient
        ctx := testAccProvider.Meta().(*ArmClient).StopContext

        if resp, err := client.Get(ctx, resourceGroup, accountName, name); err != nil {
            if utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Batch Application %q (Account Name %q / Resource Group %q) does not exist", name, accountName, resourceGroup)
            }
            return fmt.Errorf("Bad: Get on applicationClient: %+v", err)
        }

        return nil
    }
}

func testCheckAzureRMBatchApplicationDestroy(s *terraform.State) error {
    client := testAccProvider.Meta().(*ArmClient).applicationClient
    ctx := testAccProvider.Meta().(*ArmClient).StopContext

    for _, rs := range s.RootModule().Resources {
        if rs.Type != "azurerm_batch_application" {
            continue
        }

        name := rs.Primary.Attributes["name"]
        resourceGroup := rs.Primary.Attributes["resource_group_name"]
        accountName := rs.Primary.Attributes["account_name"]

        if resp, err := client.Get(ctx, resourceGroup, accountName, name); err != nil {
            if !utils.ResponseWasNotFound(resp.Response) {
                return fmt.Errorf("Bad: Get on applicationClient: %+v", err)
            }
        }

        return nil
    }

    return nil
}

func testAccAzureRMBatchApplication_basic(rInt int, location string) string {
    return fmt.Sprintf(`
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%s"
}

resource "azurerm_storage_account" "test" {
  name                   = "acctestsa-%d"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  location               = "${azurerm_resource_group.test.location}"
  accountTier            = "Standard"
  accountReplicationType = "LRS"
}

resource "azurerm_batch_account" "test" {
  name                = "acctestbatch-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  poolAllocationMode  = "BatchService"
  storageAccountId    = "${azurerm_storage_account.test.id}"
}

resource "azurerm_batch_application" "test" {
  name                = "acctestbatchapp-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  account_name        = "${azurerm_batch_account.test.name}"
}
`, rInt, location, rInt, rInt, rInt)
}
