--- !ruby/object:Provider::Ansible::Example
task: !ruby/object:Provider::Ansible::Task
  name: azure_rm_servicebussubscription
  description: SubscriptionDelete
  code:
    resource_group: myResourceGroup
    namespace_name: my
    topic_name: myTopic
    name: sdk-Subscriptions-3670
    state: absent
  